CONFIG_NFCT_PINS_AS_GPIOS=y

# EC11 Encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Mouse Emulation
CONFIG_ZMK_POINTING=y

CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=30
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_CRITICAL=10

# 7.5ms〜11.25ms の短い接続間隔を要求 / 遅延0
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6     # 6×1.25ms = 7.5ms
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=9     # 9×1.25ms = 11.25ms
CONFIG_BT_PERIPHERAL_PREF_LATENCY=0
# nRF52840 なら2M PHYを有効化（対応ホストで遅延減）
CONFIG_BT_CTLR_PHY_2M=y
